import Head from "next/head";
import ContactForm from "@/components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Contact-Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <ContactForm />
    </div>
  );
}
